name: Deploy Images to GitHub Container Registry

on: push

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.CONTAINER_REGISTRY_TOKEN}}

      - name: "Build Image and Push to Container Registry"
        run: |
          docker build . --tag ghcr.io/${{github.repository}}:${{github.ref_name}}
          docker push ghcr.io/${{github.repository}}:${{github.ref_name}}

      - name: "Build Image as latest and Push to Container Registry"
        if: github.ref == 'refs/heads/main'
        run: |
          docker build . --tag ghcr.io/${{github.repository}}:latest
          docker push ghcr.io/${{github.repository}}:latest
